### ISSUE TITLE
Training MTAN-DeepLabv3

### ISSUE THREAD

**Issue by Njuod** [lorenmt/mtan#46]
Hi,

I'm trying to run your `resnet_mtan.py` to do two semantic label tasks. I used your `utils.py` and `create_dataset.py. `

From `resnet_mtan.py` I modified the `# Task specific decoders` part as follows:

```
        for i, t in enumerate(self.tasks):
            #out[i] = F.interpolate(self.decoders[i](a_4[i]), size=out_size, mode='bilinear', align_corners=True)
            if t == 'segmentation1':
                out[i] = F.log_softmax(out[i], dim=1)
            if t == 'segmentation2':
                out[i] = F.log_softmax(out[i], dim=1)
            #if t == 'normal':
            #    out[i] = out[i] / torch.norm(out[i], p=2, dim=1, keepdim=True)
        return out
```

But I get this error (`AttributeError: 'int' object has no attribute 'log_softmax'`):

```
Parameter Space: ABS: 72062479.0, REL: 2.8847
LOSS FORMAT: SEMANTIC-1_LOSS MEAN_IOU PIX_ACC | SEMANTIC-2_LOSS MEAN_IOU PIX_ACC
Standard training strategy without data augmentation.
torch.Size([512, 512])
Traceback (most recent call last):
  File "resnet_mtan.py", line 177, in <module>
    two_task_trainer(nyuv2_train_loader,
  File "/home/models/mtan/im2im_pred/utils.py", line 359, in two_task_trainer
    train_pred = two_task_model(train_data)
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "resnet_mtan.py", line 112, in forward
    out[i] = F.log_softmax(out[i], dim=1)
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/functional.py", line 1535, in log_softmax
    ret = input.log_softmax(dim)
AttributeError: 'int' object has no attribute 'log_softmax'
```
Could you help me to solve the error?

Also, I think this line (`out[i] = F.interpolate(self.decoders[i](a_4[i]), size=out_size, mode='bilinear', align_corners=True)
`) aime to do depth prediction, but I'm not sure what the out-size variable is for. So, I remove it based on my tasks, is that right? 

Your help is greatly appreciated.

**Comment by lorenmt** [comment]
Hello. The out[i] line is to resize the output to the original input resolution. Because typically in ResNet-like architecture, we don't directly map to the original resolution as in a standard encoder-decoder style. So you shouldn't comment it.

**Comment by Njuod** [comment]
Hello, thanks for your quick reply.

Keeping that line and modifing `def forward(self, x, out_size=512):
` is raising this error

```
Parameter Space: ABS: 72062479.0, REL: 2.8847
LOSS FORMAT: SEMANTIC-21_LOSS MEAN_IOU PIX_ACC | SEMANTIC-58_LOSS MEAN_IOU PIX_ACC
Standard training strategy without data augmentation.
torch.Size([512, 512])
Traceback (most recent call last):
  File "resnet_mtan.py", line 178, in <module>
    two_task_trainer(nyuv2_train_loader,
  File "/home/models/mtan/im2im_pred/utils.py", line 359, in two_task_trainer
    train_pred = two_task_model(train_data)
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "resnet_mtan.py", line 111, in forward
    out[i] = F.interpolate(self.decoders[i](a_4[i]), size=out_size, mode='bilinear', align_corners=True)
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/models/mtan/im2im_pred/aspp.py", line 68, in forward
    res.append(conv(x))
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/models/mtan/im2im_pred/aspp.py", line 37, in forward
    x = super(ASPPPooling, self).forward(x)
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 103, in forward
    return F.batch_norm(
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/functional.py", line 1919, in batch_norm
    _verify_batch_size(input.size())
  File "/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/functional.py", line 1902, in _verify_batch_size
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])
```
do you have any ideas?

**Comment by lorenmt** [comment]
Do out_size = [512, 512] or whatever you input resolution is.

**Comment by Njuod** [comment]
Thanks!
I modified the size but the error still exists, that may be because the batch_size = 1, so I try to use a bigger batch size = 4 and it seems it works.

However, I got this error:
```Parameter Space: ABS: 72062479.0, REL: 2.8847

LOSS FORMAT: SEMANTIC-1_LOSS MEAN_IOU PIX_ACC | SEMANTIC-2_LOSS MEAN_IOU PIX_ACC

Standard training strategy without data augmentation.

Traceback (most recent call last):
  File "resnet_mtan.py", line 177, in <module>
    two_task_trainer(nyuv2_train_loader,
  File "/mtan/im2im_pred/utils.py", line 375, in two_task_trainer
    conf_mat.update(train_pred[0].argmax(1).flatten(), train_label.flatten())
AttributeError: 'list' object has no attribute 'update'
```

I am wondering if there is an official utils.py script to run with resnet_mtan.py

**Comment by lorenmt** [comment]
I think that's the error of your confusion matrix. 

Those are all minor details of implementation, I would suggest running line by line and print out the corresponding tensors to make sure each component works correctly. It shouldn't be that difficult.

**Comment by Njuod** [comment]
Thanks! and sorry for the late response. 

I'm still trying to run the code, but I stuck with the following error:
```
Traceback (most recent call last):
  File "resnet_mtan.py", line 177, in <module>
    two_task_trainer(nyuv2_train_loader,
  File "/mtan/im2im_pred/utils.py", line 422, in two_task_trainer
    test_loss = [model_fit(test_pred[0], test_label, 'semantic'),
  File "/mtan/im2im_pred/utils.py", line 23, in model_fit
    loss = F.nll_loss(x_pred, x_output, ignore_index=-1)
  File "/.conda/envs/pytorchtb/lib/python3.8/site-packages/torch/nn/functional.py", line 2112, in nll_loss
    raise ValueError('Expected input batch_size ({}) to match target batch_size ({}).'
ValueError: Expected input batch_size (20) to match target batch_size (6).
```

where 20 is the number of classes, while 6 is the batch size. What could I be doing wrong? Thanks in advance.

**Comment by lorenmt** [comment]
Hi, I think it clearly shows in the error message. Your prediction and ground-truth don't have the same batch size.

**Comment by Njuod** [comment]
Sorry to bother you. But where should I fix this? on the model script I do:

```
        self.tasks = ['segmentation1', 'segmentation2']
        self.num_out_channels = {'segmentation1': 20, 'segmentation2': 57}
        .................................. some code .........................
        # Task specific decoders
        out = [0 for _ in self.tasks]
        for i, t in enumerate(self.tasks):
            out[i] = F.interpolate(self.decoders[i](a_4[i]), size=out_size, mode='bilinear', align_corners=True)
            if t == 'segmentation1':
                out[i] = F.log_softmax(out[i], dim=1)
            if t == 'segmentation2':
                out[i] = F.log_softmax(out[i], dim=1)
            #if t == 'normal':
             #   out[i] = out[i] / torch.norm(out[i], p=2, dim=1, keepdim=True)
        return out

        .................................. some code .........................
 
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = MTANDeepLabv3()
model = torch.nn.DataParallel(model)
deeplab = model.to(device)
optimizer = optim.Adam(deeplab.parameters(), lr=1e-4)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=100, gamma=0.5)

        .................................. some code .........................

batch_size = 6
epoch = 200
```
 While in the utils script I do:

```
        # iteration for all batches
        two_task_model.train()
        train_dataset = iter(train_loader)
        conf_mat = ConfMatrix(two_task_model.module.num_out_channels['segmentation1'])
        conf_mat2 = ConfMatrix(two_task_model.module.num_out_channels['segmentation2'])

        for k in range(train_batch):
            train_data, train_label, train_label2, train_label3 = train_dataset.next()
            train_data, train_label = train_data.to(device), train_label.long().to(device)
            train_label2, train_label3 = train_label2.long().to(device), train_label3.long().to(device)

            train_pred = two_task_model(train_data)

            optimizer.zero_grad()
            train_loss = [model_fit(train_pred[0], train_label, 'semantic'),
                          model_fit(train_pred[1], train_label2, 'semantic')]
```

so, could you tell me how can I do that?

**Comment by Njuod** [comment]
The shape of x_pred is torch.Size([6, 20, 512, 512]) and the shape of x_output is torch.Size([6, 512, 512]). So, which shape of them should I keep?

**Comment by lorenmt** [comment]
If so, the shape is correct. You should have got the loss without any errors. You can quickly test this:

```
a = torch.rand(6, 20, 512, 512)
b = torch.rand(6, 512, 512).long()
print(torch.nn.functional.nll_loss(a, b))
```

**Comment by Njuod** [comment]
It prints tensor(-0.4998)
